### ISSUE TITLE
Images Not Displaying in README

### ISSUE THREAD

**Issue by Nil-Andreu** [dream-faster/krisi#69]
Hey! Interesting code here!
I started to take a look, and wanted to raise that the images from the README are not displaying for me:
<img width="951" alt="Screenshot 2023-01-11 at 16 17 29" src="https://user-images.githubusercontent.com/65730003/211843741-1d72684a-5644-4c70-a3c8-59b89f796182.png">

**Comment by Nil-Andreu** [comment]
Does this project is open for new developers?

**Comment by szemyd** [comment]
Hi @Nil-Andreu,
Thanks for pointing it out. I have fixed the ``Readme`` error now! I will continue to upload more screenshots as the project evolves.

Yes, we are happy to involve new developers :)
I've setup a new Discord Server on which we can communicate, join here: https://discord.gg/M2FXjE2t
